#!/usr/bin/env python3
# Copyright: Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

"""Embed the bundled OFL WOFF2 subsets into the ethics card stylesheet as
``@font-face`` data URIs.

The one-passage ethics card is styled by a single ``style.css`` that the importer
copies verbatim into the note type's CSS (it does NOT bundle media), so the only
way to make Source Serif 4 / IBM Plex Sans render on desktop Anki, AnkiDroid AND
in the standalone headless-Chrome proof is to inline the fonts. This reads the
real OFL WOFF2 files from ``templates/fonts/`` and rewrites the marked block in
``style.css`` in place. It is idempotent: re-running refreshes the embedded block
between the BEGIN/END sentinels.

Usage:
    out/pyenv/bin/python tools/cfa/embed_fonts.py
"""

from __future__ import annotations

import base64
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
TEMPLATES = os.path.join(REPO, "cfa", "ethics_pairs", "templates")
CSS = os.path.join(TEMPLATES, "style.css")
FONTS = os.path.join(TEMPLATES, "fonts")

MARKER = "/* __CFA_BUNDLED_FONTS__ */"
BEGIN = (
    "/* __CFA_FONTS_BEGIN__ (generated by tools/cfa/embed_fonts.py — do not edit) */"
)
END = "/* __CFA_FONTS_END__ */"

# (family, weight, filename). Only the weights the card actually uses.
FACES = [
    ("Source Serif 4", 400, "source-serif-4-latin-400.woff2"),
    ("IBM Plex Sans", 400, "ibm-plex-sans-latin-400.woff2"),
    ("IBM Plex Sans", 500, "ibm-plex-sans-latin-500.woff2"),
]


def _face(family: str, weight: int, filename: str) -> str:
    with open(os.path.join(FONTS, filename), "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    return (
        "@font-face {\n"
        f"  font-family: '{family}';\n"
        "  font-style: normal;\n"
        f"  font-weight: {weight};\n"
        "  font-display: swap;\n"
        f"  src: url(data:font/woff2;base64,{b64}) format('woff2');\n"
        "}\n"
    )


def build_block() -> str:
    faces = "".join(_face(*f) for f in FACES)
    return f"{BEGIN}\n{faces}{END}"


def main() -> int:
    css = open(CSS, encoding="utf-8").read()
    block = build_block()
    if BEGIN in css and END in css:
        pre = css[: css.index(BEGIN)]
        post = css[css.index(END) + len(END) :]
        css = pre + block + post
    elif MARKER in css:
        css = css.replace(MARKER, block)
    else:
        raise SystemExit(
            f"no font marker found in {CSS} (expected {MARKER!r} or BEGIN/END sentinels)"
        )
    with open(CSS, "w", encoding="utf-8") as f:
        f.write(css)
    kb = len(block) / 1024
    print(f"embedded {len(FACES)} @font-face rules ({kb:.1f} KB) into {CSS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
